const messages = ["I promise the rest of the day is going to be nicer",
                "Reminder to be kinder to yourself",
                "If you just wanted to receive nice things, you could've texted me.",
                "It's okay to take a break, rest is productive too",
                "You've got this, eventually, probably.",
                "I hope something makes you laugh today and you tell me about it",
                "The universe cooked and smiled when it made you, you'll get through this",
                "Drink water btw, the bottle has been really lonely",
                "You are being thought of, fondly.",
                "Breathe, you'll get this done. you just have to let yourself do it without criticism",
                "I don't think you've achieved the smile count for today, say eeeeeee.",
                "You're supposed to get me a chocolate if you see this. No cheating.",
                "You tapped again. Awww",
                "You make ordinary feel nice.",
                "A pigeon somewhere is rooting for you. And another one is shitting on a car at the same time.",
                "You could help the world by smiling more.",
                "This is a drum roll. Imagine it. Deal with the no sound.",
                "Awww, did you like tapping this?",
                "Sit up please, your neck will thank you.",
                "The plant asks you how you're doing. It is actually interested btw.",
                "You should get yourself a chocolate. And probably me too.",
                "it's okayyy, I see youu. And as always, I like what I see.",
                "You're really talking to a plant.",
                "Saying boo boo baa baaa out loud three times brightens your day.",
                "Water, drink waterrrr.",
                "You are doing better than your brain is admitting.",
                "Congratulations. You found another sentence.",
                "The council has decided you deserve a soft day, every day.",
                "The plant says hi. I say hiiii.",
                "Applauseee. If you can't hear it, let me know, I'll call and clap",
                "Hydration reminder. Come on, a PLANT is telling you to drink water.",
                "May the force be with you.",
                "Reminder that your lower back exists and you should probably pay attention to it.",
                "You make everything softer. And you deserve softness too"]


var idx = Math.floor(Math.random() * messages.length)
document.getElementById("message").textContent = messages[idx];
